ParserError in file /mnt/share/PROJECTS/SomSOM/Step_III/SAMSARA/Snakefile.smk, line 13:
while parsing a block mapping
  in "config_test.yaml", line 25, column 11
expected <block end>, but found '<scalar>'
  in "config_test.yaml", line 29, column 19
  File "/mnt/share/PROJECTS/SomSOM/Step_III/SAMSARA/Snakefile.smk", line 13, in <module>
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 125, in safe_load
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 81, in load
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
